name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
      - hotfix/*
      - dev
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "PROJECT_ID=bizpharma-prod" >> $GITHUB_ENV
            echo "SA_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_BIZPHARMA_PROD }}" >> $GITHUB_ENV
            echo "BUILD_ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "PROJECT_ID=bizpharma-staging" >> $GITHUB_ENV
            echo "SA_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_BIZPHARMA_STAGING }}" >> $GITHUB_ENV
            echo "BUILD_ENV=staging" >> $GITHUB_ENV
          else
            # Default to dev project for other branches/hotfixes
            echo "PROJECT_ID=bizpharma-4e73a" >> $GITHUB_ENV
            echo "SA_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_BIZPHARMA_4E73A }}" >> $GITHUB_ENV
            echo "BUILD_ENV=development" >> $GITHUB_ENV
          fi

      - name: Build Web App
        run: flutter build web --release --dart-define=ENVIRONMENT=${{ env.BUILD_ENV }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.SA_KEY }}'
          channelId: live
          projectId: ${{ env.PROJECT_ID }}
